#!/bin/bash

OUTPUT_PATH="$1"
VERSION="$2"
BRANCH="$3"
SHA="$4"

# Debian packaging requires that package versions begin with a digit
if [[ ! "${VERSION}" =~ ^[0-9]+.* ]]; then
  echo "Error: Versions must begin with a digit!"
  exit 1
fi

# Emit version metadata to appropriate files.

# Include machine-parseable metadata JSON file.
printf '{
"version": "%s",
"branch": "%s",
"sha": "%s"
}' "$VERSION" "$BRANCH" "$SHA" > "$OUTPUT_PATH/.metadata.json"

# Set version info for plutonium binaries.
for cmd in \
  cmd/influxd \
  cmd/influxd-ctl \
  cmd/influxd-meta \
  ; do
printf 'package main

// Code generated by influxdata/releng tooling. DO NOT EDIT.

func init() {
	version = "%s"
	branch = "%s"
	commit = "%s"
}' "$VERSION" "$BRANCH" "$SHA" | tee "$OUTPUT_PATH/$cmd/version.generated.go"
done


